SELECT V_DESCODIGO, N_DESNOMBRE, V_DESVALOR, V_DESUSUREG, V_DESUSUMOD, D_FECREGIS, D_FECMODIF, V_DESHOSTREG, V_DESIPREG
FROM SGCPESYS.GCPETBX_PARAMETRO WHERE V_DESCODIGO = '123454321';
-- Afecta 1 registro
INSERT INTO SGCPESYS.GCPETBX_PARAMETRO
(V_DESCODIGO, N_DESNOMBRE, V_DESVALOR, V_DESUSUREG, V_DESUSUMOD, D_FECREGIS, D_FECMODIF, V_DESHOSTREG, V_DESIPREG)
VALUES('123454321', 'Token-Confidencial', '33fc12a0bce48cb2e800858d694e5f9b704c08b4e17367a48ef897f8e47ff152', USER, USER, SYSDATE, SYSDATE, SYS_CONTEXT('USERENV', 'HOST'), SYS_CONTEXT('USERENV','IP_ADDRESS'));
COMMIT;
SELECT V_DESCODIGO, N_DESNOMBRE, V_DESVALOR, V_DESUSUREG, V_DESUSUMOD, D_FECREGIS, D_FECMODIF, V_DESHOSTREG, V_DESIPREG
FROM SGCPESYS.GCPETBX_PARAMETRO WHERE V_DESCODIGO = '123454321';
