"""
Django settings for emprende project.

Generated by 'django-admin startproject' using Django 3.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path

from corsheaders.defaults import default_headers, default_methods

from apps.common.middleware import RequestMiddleware

BASE_DIR = Path(__file__).resolve().parent.parent.parent

SHARE_DIR = os.environ.get('SHARE_DIR', r'\\192.168.21.163\archivos_compartidos')

SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

DEBUG = True

# Evitar eliminación de tablas en el esquema
PROTECT_DELETES = True

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '*').split(',')

DJANGO_APPS = [
    'django.contrib.messages',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.staticfiles',
]

THIRD_PARTY_APPS = [
    'rest_framework',
    'corsheaders',
    'django_filters'
]

LOCAL_APPS = [
    'apps.common',
    'apps.seguridad',
    'apps.programacion',
    'apps.modelsext',
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    'concurrency.middleware.ConcurrencyMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'apps.common.middleware.RequestMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [str(BASE_DIR.joinpath('apps/templates'))],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': os.environ.get('DB_NAME_URL'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASS'),
    },
    'planillas':{
        'ENGINE': 'django.db.backends.oracle',
        'NAME': os.environ.get('DB_NAME_PLANILLAS'), #DB_NAME_PLANILLAS=192.168.105.121:1539/plelpdev;
        'USER': os.environ.get('DB_USER_PLANILLAS'), #DB_USER_PLANILLAS=UC_PSORUELAS;
        'PASSWORD': os.environ.get('DB_PASS_PLANILLAS'), #DB_PASS_PLANILLAS=dev$180720245
    }
    #DB_NAME_PLANILLAS=192.168.105.121:1539/plelpdev;DB_USER_PLANILLAS=UC_PSORUELAS;DB_PASS_PLANILLAS=dev$180720245;
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
LOGIN_ATTEMPT_CAPTCHA = os.environ.get('LOGIN_ATTEMPT_CAPTCHA', '100')

REST_FRAMEWORK = {
    'DATETIME_FORMAT': '%d/%m/%Y %H:%M%S',
    'DATE_INPUT_FORMATS': [
        '%d/%m/%Y',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'apps.seguridad.auth.CustomAuthenticationTemporal',
    ),
    #'DEFAULT_THROTTLE_CLASSES': (
    #    'rest_framework.throttling.AnonRateThrottle',
    #    'rest_framework.throttling.UserRateThrottle'
    #),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '500/minute',
        'user': '1000/minute',
        'loginAttempts': '{}/hr'.format(LOGIN_ATTEMPT_CAPTCHA),

    }
}

LANGUAGE_CODE = 'es-PE'

TIME_ZONE = 'America/Lima'

USE_I18N = True

USE_L10N = False

USE_TZ = False

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATIC_URL = '/static/'

STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/login/'

# Variables Internas del Sistema

CODIGO_SISTEMA = os.environ.get('CODIGO_SISTEMA')
CODIGO_SISTEMA_WS = os.environ.get('CODIGO_SISTEMA_WS')
LDR_HOST_API = os.environ.get('LDR_HOST_API')
LDR_PATH_API = os.environ.get('LDR_PATH_API')
WSM_HOST_API = os.environ.get('WSM_HOST_API')
WSM_PATH_API = os.environ.get('WSM_PATH_API')
WSR_PATH_API = os.environ.get('WSR_PATH_API')
WSR_RP_PATH_API = os.environ.get('WSR_RP_PATH_API')
WSR_SEC_PATH_API = os.environ.get('WSR_SEC_PATH_API')
WSR_USERNAME_API = os.environ.get('WSR_USERNAME_API')
WSR_PASSWORD_API = os.environ.get('WSR_PASSWORD_API')

AUTH_USER_MODEL = 'seguridad.User'
AUTH_GROUP_MODEL = 'seguridad.Group'
AUTH_PERMISSION_MODEL = 'seguridad.Permission'

SECRET_KEY_JWT = os.environ.get(
    'SECRET_KEY_JWT',
    'MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCIE6a1NyEFe7qCDFrvWFZiAlY1ttE5596w5dLjNSaHlKGv8AXbKg/f8yKY9fKAJ5BKoeWEkPPjpn1t9QQAZYzqH9KNOFigMU8pSaRUxjI2dDvwmu8ZH6EExY+RfrPjQGmeliK18iFzFgBtf0eH3NAW3P0000Zz+cuNnVtE9lrYQIDAQAB',  # noqa
)

SE_HOST_API = os.environ.get('SE_HOST_API')
SE_TOKEN_API = os.environ.get('SE_TOKEN_API')
SE_ID_APLICACION = os.environ.get('SE_ID_APLICACION')
SE_HOST_API_SE = os.environ.get('SE_HOST_API_SE')
SE_TOKEN_API_SE = os.environ.get('SE_TOKEN_API_SE')

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_HEADERS = list(default_headers)

CORS_ALLOW_METHODS = list(default_methods)

CORS_ALLOWED_HOSTS = os.environ.get(
    'CORS_ALLOWED_HOSTS',
    'http://localhost:8080,http://192.168.41.23,http://127.0.0.1:8080,http://192.168.41.23:5173',
).split(',')


CORS_ALLOWED_ORIGINS = os.environ.get('CORS_ALLOWED_ORIGINS_HOSTS',
                                      'http://localhost:8080,http://127.0.0.1:8080').split(',')

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'notificadesa@trabajo.gob.pe')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', 'desarrollo2020$')

ID_DB_ROL_DEPENDENCIA = os.environ.get('ID_DB_ROL_DEPENDENCIA', '002')
ID_DB_ROL_ROTACION = os.environ.get('ID_DB_ROL_ROTACION', '003')
ID_DB_ROL_TRABAJADOR = os.environ.get('ID_DB_ROL_TRABAJADOR', '004')
ID_DB_ROL_RRHH = os.environ.get('ID_DB_ROL_RRHH', '005')

SKIP_VALIDAR_VERIFICACION = os.environ.get('SKIP_VALIDAR_VERIFICACION', '0')

FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://dscalvir.trabajo.gob.pe')

RE_CAPTCHA_SITE_KEY = os.environ.get('RE_CAPTCHA_SITE_KEY', '6LcNc9koAAAAAJRgalYJWARpxeJoZK-jK6palw6Q')
RE_CAPTCHA_SECRET_KEY = os.environ.get('RE_CAPTCHA_SECRET_KEY', '6LcNc9koAAAAAJGQVWPOAca22f9yz0sAgZQN1ZJ4')
